(ns kotoba.render.pipeline-specs
  "EDN authority for the native open-world render-pipeline specs (cull /
   depth / blend policy per named pipeline). Ported from
   `kami-render/src/pipeline_specs.rs`'s `PIPELINE_SPECS` const (itself
   GENERATED by `bb gen-pipeline-specs` from `kami.pipelines/native-pipelines`
   — single-sourced with the web side).

   Loaded from `resources/kotoba/render/pipeline_specs.edn`, which IS this
   port's authority copy (JVM resource loading, matching the
   `kami-scene-contracts` convention in this monorepo). JVM-only (`.clj`,
   not `.cljc`) — `io/resource` has no portable CLJS equivalent here.

   The resource is stored as Datomic/Datascript tx-data (one entity per
   pipeline, attrs namespaced `:kotoba.render.pipeline-specs/*`) so it can
   be `d/transact`-ed directly; `pipeline-specs` reconstitutes the original
   bare-keyed maps below for this ns's own callers."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]))

(def resource-path "kotoba/render/pipeline_specs.edn")

(defn- reconstitute-entity
  "Drop :db/id and strip the namespace off each attr key, e.g.
   :kotoba.render.pipeline-specs/name -> :name."
  [entity]
  (into {} (map (fn [[k v]] [(keyword (name k)) v])) (dissoc entity :db/id)))

(defn pipeline-specs
  "Vector of `{:name :shader :cull :depth-write :depth-compare :blend}`
   maps, one per named render pipeline."
  []
  (let [resource (io/resource resource-path)]
    (when-not resource
      (throw (ex-info "missing pipeline-specs resource" {:path resource-path})))
    (mapv reconstitute-entity (edn/read-string (slurp resource)))))

(defn by-name
  "Look up a pipeline spec by `:name` (string)."
  [name]
  (first (filter #(= (:name %) name) (pipeline-specs))))
