(ns kotoba.render.pipeline-specs
  "EDN authority for the native open-world render-pipeline specs (cull /
   depth / blend policy per named pipeline). Ported from
   `kami-render/src/pipeline_specs.rs`'s `PIPELINE_SPECS` const (itself
   GENERATED by `bb gen-pipeline-specs` from `kami.pipelines/native-pipelines`
   — single-sourced with the web side).

   Loaded from `resources/kotoba/render/pipeline_specs.edn`, which IS this
   port's authority copy (JVM resource loading, matching the
   `kami-scene-contracts` convention in this monorepo). JVM-only (`.clj`,
   not `.cljc`) — `io/resource` has no portable CLJS equivalent here."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]))

(def resource-path "kotoba/render/pipeline_specs.edn")

(defn pipeline-specs
  "Vector of `{:name :shader :cull :depth-write :depth-compare :blend}`
   maps, one per named render pipeline."
  []
  (let [resource (io/resource resource-path)]
    (when-not resource
      (throw (ex-info "missing pipeline-specs resource" {:path resource-path})))
    (edn/read-string (slurp resource))))

(defn by-name
  "Look up a pipeline spec by `:name` (string)."
  [name]
  (first (filter #(= (:name %) name) (pipeline-specs))))
